// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCy7TAmQ7nBcAi6uEIdvy6DXUecarHgqI',
    appId: '1:1019989784253:web:f9e769f1b9707d24fea9d4',
    messagingSenderId: '1019989784253',
    projectId: 'proyojon-d3132',
    authDomain: 'proyojon-d3132.firebaseapp.com',
    storageBucket: 'proyojon-d3132.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwMQf2JX48yedP0Yj2eNU-LcyRw0Wz8hE',
    appId: '1:1019989784253:android:5aab5f6da842a22ffea9d4',
    messagingSenderId: '1019989784253',
    projectId: 'proyojon-d3132',
    storageBucket: 'proyojon-d3132.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJxlk82T2psFGfsvd4H3b7nCqCGluc4ZM',
    appId: '1:1019989784253:ios:1ca2dea8f49fa5abfea9d4',
    messagingSenderId: '1019989784253',
    projectId: 'proyojon-d3132',
    storageBucket: 'proyojon-d3132.firebasestorage.app',
    iosBundleId: 'com.example.proyojony',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJxlk82T2psFGfsvd4H3b7nCqCGluc4ZM',
    appId: '1:1019989784253:ios:1ca2dea8f49fa5abfea9d4',
    messagingSenderId: '1019989784253',
    projectId: 'proyojon-d3132',
    storageBucket: 'proyojon-d3132.firebasestorage.app',
    iosBundleId: 'com.example.proyojony',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCy7TAmQ7nBcAi6uEIdvy6DXUecarHgqI',
    appId: '1:1019989784253:web:e3f8be20c2d3d792fea9d4',
    messagingSenderId: '1019989784253',
    projectId: 'proyojon-d3132',
    authDomain: 'proyojon-d3132.firebaseapp.com',
    storageBucket: 'proyojon-d3132.firebasestorage.app',
  );

}